title: portfolio
subtitle: A Portfolio Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: Projects & Publications
      url: /pap
    - text: Blog
      url: /blog
    - text: CV
      url: /cv
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Siddhant Singh
author_bio: Hi, I am Siddhant S. Singh.
author_email: "siddhss20@iitk.ac.in"
author_location: India
author_website_url: "https://sujaykundu.com"
typewrite-text: devlopr is a jekyll framework built for developers. You can edit this in _config.yml file
hero_cover_img: sample_cover.png # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Wells Fargo
              company_logo: wells_fargo.png
              company_url: https://www.wellsfargo.com
              designation: Software Engineer
              description: Created front-end of an anti credit card fraud system using react.
              visibility: true

# Education
author_education_details:
              - college_logo: iitk_logo.png
                college_name: IIT Kanpur
                college_url: https://www.iitk.ac.in/
                college_degree: B.S and M.S
                description:  Mathematics and Scientific Computing
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: porl.png
                project_title: Portfolio Optimization using DL and RL
                project_description: Solved for the efficient frontier, estimated portfolio betas and correlations, predicted price movements with deep learning models, conducted a literature review on DWT and technical indicators, and planned future work on Reinforcement Learning for portfolio management.
                project_url: https://github.com/siddhant7876/Portfolio_optimization_7876
                visibility: true
              - project_thumbnail: magtrl.png
                project_title: Multi-Agent game theoretic RL simulation
                project_description: Conducted literature review on Reinforcement Learning, Game Theory in biology and economics, and altruism in animals. Derived insights into natural altruism and agent strategies. Built a Deep Q-network with Leaky ReLU in PyTorch for agent decision-making. Demonstrated the value of altruism through extensive simulations across various species.
                project_url: https://github.com/siddhant7876/RL_project/tree/master/why-would-you-do-that
                visibility: true
              - project_thumbnail: simda.png
                project_title: Statistical Simulation and data analysis
                project_description: Implemented OLLLTN distribution for bimodal data in (0,1), validated via Monte Carlo simulations, and optimized convergence. Applied to Human Development Index data, showing superior AIC and GD performance over other models.
                project_url: Coming Soon
                visibility: true
              - project_thumbnail: mbmm.png
                project_title: Modeling data with Bayesian Mixed-effects model
                project_description: Analyzed dragonfly population data, justifying Zero-Inflated Bi-variate Geometric (ZIBGe) as the GLMM model. Used MCMC with JAGS for parameter estimation, confirmed convergence, and proved ZIBGe's superiority over BZIP using DIC.
                project_url: Coming Soon
                visibility: true
              - project_thumbnail: forcnn.png
                project_title: Faster RCNN for object detection
                project_description: Reviewed papers on R-CNN and Faster R-CNN, analyzing time complexities and computational efficiency. Trained and fine-tuned a Faster R-CNN model on Kaggle's fruit detection dataset, achieving 88% accuracy using PyTorch.
                project_url: https://github.com/siddhant7876/Faster-RCNN
                visibility: true
              - project_thumbnail: algo.png
                project_title: Algo 101x
                project_description: Implemented algorithms for binary search, hashing, collision handling, Sieve of Eratosthenes, factorization, and Dynamic Programming with bitmasking. Explored range query techniques (sqrt decomposition, segment trees, sparse tables, binary indexed trees) and variations of the Knapsack problem, binary lifting, and Union-Find.
                project_url: Coming Soon
                visibility: true

#Publications
author_publication_details:
                  - publication_thumbnail: cultllm.png
                    publication_title: Towards Measuring and Modeling “Culture” in LLMs A Survey
                    publication_description: Surveyed over 90 recent papers on cultural representation in large language models (LLMs). Noted that studies lack a clear definition of "culture," using proxies like demographic and semantic aspects instead. Found gaps in exploring diverse cultural facets, robustness of probing methods, and the impact of cultural misrepresentation in LLM applications.
                    publication_links: https://doi.org/10.48550/arXiv.2403.15412
                    visibility: true



# social links
twitter_username: siddhant7876
github_username:  siddhant7876
instagram_username: siddhant_7876
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: siddhant7876

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_publication_details : true
# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "cv"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
